import type { Locale } from "@/lib/i18n";

export const pageCopy = {
  ko: {
    nav: {
      start: "시작하기",
      home: "홈",
      backHome: "홈으로",
      retry: "다시 테스트하기",
    },
    localeNames: {
      ko: "한국어",
      en: "English",
      ja: "日本語",
    },
    home: {
      eyebrow: "DRAMA CASTING TEST",
      title: "얼굴 한 장으로 보는 드라마 캐스팅 테스트",
      heroEyebrow: "캐릭터 중심 엔터테인먼트",
      heroTitleA: "당신은 어떤",
      heroTitleB: "드라마 속 역할과 닮아 있을까",
      heroDescription:
        "이 서비스는 외모를 평가하지 않습니다. 얼굴 사진에서 읽히는 분위기와 무드를 바탕으로, 잘 어울리는 장르와 캐릭터를 가볍게 추천하는 콘텐츠형 웹앱입니다.",
      startTest: "테스트 시작하기",
      noticeLink: "이용 전 확인",
      stepsTitle: "이렇게 진행돼요",
      steps: [
        { title: "사진 올리기", description: "얼굴이 잘 보이는 사진 한 장만 올리면 준비 끝." },
        { title: "분위기 확인", description: "사진 상태를 먼저 보고, 결과를 만들기 좋은지 가볍게 체크해요." },
        { title: "캐릭터 받기", description: "잘 어울리는 장르와 메인 캐릭터를 카드로 보여드려요." },
      ],
      features: [
        { title: "사진 한 장 업로드", description: "정면에 가까운 인물 사진으로 시작합니다. 업로드 직후 사진 상태를 먼저 확인합니다." },
        { title: "장르와 역할 추천", description: "로맨스, 범죄, 청춘, 법정 등 여러 장르 중 어떤 분위기가 잘 맞는지 보여줍니다." },
        { title: "공유 카드 제공", description: "결과를 카드 형태로 정리해 링크 복사와 공유하기까지 바로 이어집니다." },
      ],
      noticeTitle: "이용 전 안내",
      notices: [
        "외모 점수화, 미남/미녀 판정, 상하위 판단은 하지 않습니다.",
        "결과는 엔터테인먼트용 캐릭터 추천이며 실제 성격 진단이 아닙니다.",
        "업로드한 사진은 장기 저장하지 않고 결과 생성용으로만 잠시 사용합니다.",
      ],
    },
    upload: {
      eyebrow: "UPLOAD",
      title: "사진을 올리고 캐스팅 결과를 받아보세요",
    },
    result: {
      eyebrow: "RESULT",
      title: "드라마 캐스팅 결과",
    },
    uploadPanel: {
      eyebrow: "사진 업로드",
      title: "얼굴 사진 한 장으로 캐스팅 결과 보기",
      description: "셀카 한 장만 올리면 끝. 무드랑 분위기를 읽어서 드라마 속 어떤 역할이 잘 붙는지 가볍고 재밌게 보여드릴게요.",
      uploadTitle: "사진 올리기",
      uploadHint: "얼굴이 잘 보이는 사진이면 가장 자연스럽게 나와요.",
      chooseLibrary: "앨범에서 고르기",
      mobileCamera: "스마트폰 카메라로 찍기",
      desktopCamera: "PC 웹캠으로 찍기",
      desktopCameraLoading: "카메라 여는 중...",
      mobileHint: "스마트폰에서는 바로 카메라 촬영이 열리고, 필요하면 앨범 사진도 고를 수 있어요.",
      desktopHint: "PC에서는 앨범에서 고르거나 웹캠으로 바로 찍을 수 있어요.",
      webcamTitle: "웹캠 촬영",
      close: "닫기",
      useShot: "지금 사진으로 사용하기",
      cancel: "취소",
      selectedFile: "선택한 파일",
      noFile: "아직 선택한 사진이 없어요",
      characterTone: "캐릭터 톤 선택",
      toneHint: "헷갈리지 않게 결과 방향을 먼저 골라 주세요. 이 선택에 맞춰 캐릭터를 추천해요.",
      toneMale: "남성 캐릭터 쪽",
      toneFemale: "여성 캐릭터 쪽",
      quickCheck: "업로드 전 간단 확인",
      checking: "사진을 바로 써도 괜찮은지 가볍게 보고 있어요. 잠깐만 기다려 주세요.",
      quickCheckHint: "얼굴이 잘 보이는 사진인지 간단히 확인해요. 이 단계가 건너뛰어져도 결과는 볼 수 있어요.",
      notesTitle: "가볍게 체크",
      notes: [
        "외모 평가는 하지 않고 분위기랑 캐릭터 느낌만 봐요.",
        "한 사람만 나온 사진일수록 결과가 더 깔끔해요.",
        "너무 흐리면 다시 올려 달라고 안내할 수 있어요.",
      ],
      submit: "캐스팅 결과 보기",
      submitting: "결과를 준비하고 있어요...",
      webcamNotSupported: "이 브라우저에서는 웹캠 촬영을 지원하지 않아요.",
      webcamOpenError: "카메라를 열지 못했어요. 권한을 확인하거나 사진 업로드를 이용해 주세요.",
      captureError: "촬영 이미지를 준비하지 못했어요. 다시 시도해 주세요.",
      filePrepError: "사진을 준비하는 중 문제가 생겼어요. 다시 올려 주세요.",
    },
    share: {
      native: "기본 공유",
      instagram: "인스타그램",
      facebook: "페이스북",
      copyLink: "링크 복사",
      kakao: "카카오톡",
      kakaoView: "결과 보기",
      instagramHint: "인스타그램은 문구 복사 후 앱에서 붙여 넣는 방식이에요.",
      kakaoHint: "카카오톡은 키를 넣으면 바로 공유돼요.",
      copiedLink: "링크를 복사했어요.",
      copiedResultLink: "결과 링크를 복사했어요.",
      copiedInstagram: "인스타그램용 문구를 복사했어요.",
      copiedKakao: "카카오톡용 문구를 복사했어요.",
    },
    resultUi: {
      loadingTitle: "결과를 만드는 중이에요",
      emptyEyebrow: "결과를 아직 만들지 못했어요",
      emptyTitle: "업로드부터 다시 시작해 주세요",
      emptyDescription: "사진을 다시 올리면 캐릭터 결과를 바로 보여드릴게요.",
      headerEyebrow: "드라마 캐스팅 테스트",
      headerTitle: "당신의 캐릭터 결과가 나왔어요",
      friendShare: "친구한테 보내기 좋은 한마디",
      works: "이런 작품 분위기도 잘 어울려요",
      actors: "비슷한 무드의 배우 레퍼런스",
      actorsHint: "닮은꼴이 아니라, 이번 결과와 함께 떠오르는 분위기 레퍼런스예요.",
      storageNote: "사진은 브라우저 안에서만 잠깐 쓰고 따로 오래 보관하지 않아요.",
      entertainmentNote: "이건 재미로 보는 캐릭터 테스트예요. 외모 평가나 등급 매기기는 하지 않아요.",
    },
    footer: {
      privacyTitle: "개인정보 안내",
      privacyBody: "업로드한 사진은 결과 생성에만 잠깐 쓰고 장기 저장하지 않습니다.",
      termsTitle: "이용 안내",
      termsBody: "이 서비스는 엔터테인먼트용 캐릭터 추천이며, 실제 진단이나 판정 서비스가 아닙니다.",
      contactTitle: "문의",
      address: "Goyang-si, Gyeonggi-do, South Korea",
      email: "caelestis@empas.com",
    },
  },
  en: {
    nav: { start: "Start", home: "Home", backHome: "Back to Home", retry: "Try Again" },
    localeNames: { ko: "한국어", en: "English", ja: "日本語" },
    home: {
      eyebrow: "DRAMA CASTING TEST",
      title: "A Drama Casting Test from One Photo",
      heroEyebrow: "Character-first entertainment",
      heroTitleA: "Which",
      heroTitleB: "drama role fits your vibe?",
      heroDescription:
        "This service does not rate appearance. It reads the mood and impression of a face photo and lightly recommends genres and character types that fit best.",
      startTest: "Start Test",
      noticeLink: "Before You Start",
      stepsTitle: "How it works",
      steps: [
        { title: "Upload a photo", description: "Start with one photo where the face is easy to see." },
        { title: "Quick mood check", description: "We do a light check first to see if the photo is ready for results." },
        { title: "Get your character", description: "You get a main character card and the top matching genres." },
      ],
      features: [
        { title: "One-photo upload", description: "Start with a face photo close to the front. We check the photo briefly right after upload." },
        { title: "Genre and role match", description: "See which genres such as romance, crime, youth, and legal fit your overall vibe." },
        { title: "Shareable result card", description: "Your result is organized into a card you can share right away." },
      ],
      noticeTitle: "Before you start",
      notices: [
        "We do not score appearance or rank people.",
        "This is entertainment-focused character matching, not a real personality diagnosis.",
        "Uploaded photos are only used briefly to generate the result and are not stored long-term.",
      ],
    },
    upload: { eyebrow: "UPLOAD", title: "Upload a photo and get your casting result" },
    result: { eyebrow: "RESULT", title: "Drama Casting Result" },
    uploadPanel: {
      eyebrow: "PHOTO UPLOAD",
      title: "Get a casting result from one face photo",
      description: "Just upload one selfie. We read the overall mood and show which drama role fits best in a fun, lightweight way.",
      uploadTitle: "Upload a photo",
      uploadHint: "A photo where your face is easy to see usually gives the cleanest result.",
      chooseLibrary: "Choose from library",
      mobileCamera: "Use phone camera",
      desktopCamera: "Use webcam",
      desktopCameraLoading: "Opening camera...",
      mobileHint: "On mobile, this can open the front camera directly, or you can choose a photo from your gallery.",
      desktopHint: "On desktop, you can choose a file or use your webcam.",
      webcamTitle: "Webcam capture",
      close: "Close",
      useShot: "Use this shot",
      cancel: "Cancel",
      selectedFile: "Selected file",
      noFile: "No photo selected yet",
      characterTone: "Character tone",
      toneHint: "Choose the direction first so the result stays consistent with the roles you want to see.",
      toneMale: "More male roles",
      toneFemale: "More female roles",
      quickCheck: "Quick check before upload",
      checking: "We are doing a quick check to see if this photo is ready. One moment.",
      quickCheckHint: "We do a light check to see if the face is clearly visible. Even if this step is skipped, you can still get a result.",
      notesTitle: "Quick notes",
      notes: [
        "We do not rate appearance. We only look at mood and character feel.",
        "A photo with one person usually gives a cleaner result.",
        "If the photo is too blurry, we may ask for another one.",
      ],
      submit: "See my result",
      submitting: "Preparing your result...",
      webcamNotSupported: "This browser does not support webcam capture.",
      webcamOpenError: "Could not open the camera. Please check permissions or upload a photo instead.",
      captureError: "Could not prepare the captured image. Please try again.",
      filePrepError: "Something went wrong while preparing the photo. Please try again.",
    },
    share: {
      native: "Share",
      instagram: "Instagram",
      facebook: "Facebook",
      copyLink: "Copy link",
      kakao: "KakaoTalk",
      kakaoView: "View result",
      instagramHint: "For Instagram, we copy the caption first so you can paste it in the app.",
      kakaoHint: "Add a Kakao key to enable direct sharing.",
      copiedLink: "Link copied.",
      copiedResultLink: "Result link copied.",
      copiedInstagram: "Instagram caption copied.",
      copiedKakao: "KakaoTalk text copied.",
    },
    resultUi: {
      loadingTitle: "Building your result",
      emptyEyebrow: "We couldn't load the result yet",
      emptyTitle: "Please start from upload again",
      emptyDescription: "Upload a photo again and we will rebuild your character result.",
      headerEyebrow: "DRAMA CASTING TEST",
      headerTitle: "Your character result is ready",
      friendShare: "A line worth sharing",
      works: "Works with a similar vibe",
      actors: "Actor mood references",
      actorsHint: "These are mood references, not look-alike matches.",
      storageNote: "Your photo is only used briefly in the browser and is not stored long-term.",
      entertainmentNote: "This is an entertainment-style character test. It does not rate appearance or rank people.",
    },
    footer: {
      privacyTitle: "Privacy",
      privacyBody: "Uploaded photos are only used briefly to generate the result and are not stored long-term.",
      termsTitle: "Terms",
      termsBody: "This service is for entertainment-style character matching and is not a real diagnosis or evaluation tool.",
      contactTitle: "Contact",
      address: "Goyang-si, Gyeonggi-do, South Korea",
      email: "caelestis@empas.com",
    },
  },
  ja: {
    nav: { start: "はじめる", home: "ホーム", backHome: "ホームへ", retry: "もう一度試す" },
    localeNames: { ko: "한국어", en: "English", ja: "日本語" },
    home: {
      eyebrow: "DRAMA CASTING TEST",
      title: "1枚の写真で見るドラマキャスティングテスト",
      heroEyebrow: "キャラクター重視のエンタメ",
      heroTitleA: "あなたはどんな",
      heroTitleB: "ドラマの役に似合う？",
      heroDescription:
        "このサービスは見た目を評価しません。顔写真から伝わる雰囲気やムードをもとに、似合うジャンルやキャラクターを気軽におすすめします。",
      startTest: "テストを始める",
      noticeLink: "利用前の案内",
      stepsTitle: "こんな流れです",
      steps: [
        { title: "写真をアップロード", description: "顔が見えやすい写真を1枚選べば準備完了です。" },
        { title: "かんたんチェック", description: "結果を出しやすい写真かどうかを軽く確認します。" },
        { title: "キャラクター結果", description: "似合うジャンルとメインキャラクターをカードで見せます。" },
      ],
      features: [
        { title: "写真1枚でOK", description: "正面に近い顔写真から始めます。アップロード直後に写真の状態を軽く確認します。" },
        { title: "ジャンルと役柄のおすすめ", description: "ロマンス、犯罪、青春、法廷などの中から、どんな雰囲気が合うかを見せます。" },
        { title: "共有しやすいカード", description: "結果をカード形式でまとめて、そのまま共有できます。" },
      ],
      noticeTitle: "利用前の案内",
      notices: [
        "見た目の点数化や順位づけは行いません。",
        "結果はエンタメ向けのキャラクターおすすめであり、性格診断ではありません。",
        "アップロードした写真は結果生成のために短時間だけ使い、長期保存はしません。",
      ],
    },
    upload: { eyebrow: "UPLOAD", title: "写真をアップロードしてキャスティング結果を見る" },
    result: { eyebrow: "RESULT", title: "ドラマキャスティング結果" },
    uploadPanel: {
      eyebrow: "写真アップロード",
      title: "顔写真1枚でキャスティング結果を見る",
      description: "セルカを1枚アップロードするだけ。全体のムードを見て、どんなドラマの役が似合うかを気軽に見せます。",
      uploadTitle: "写真をアップロード",
      uploadHint: "顔がはっきり見える写真のほうが自然な結果になりやすいです。",
      chooseLibrary: "アルバムから選ぶ",
      mobileCamera: "スマホカメラで撮る",
      desktopCamera: "PCウェブカメラで撮る",
      desktopCameraLoading: "カメラを開いています...",
      mobileHint: "スマホではそのままカメラ撮影が開き、必要ならアルバム写真も選べます。",
      desktopHint: "PCではファイル選択かウェブカメラ撮影が使えます。",
      webcamTitle: "ウェブカメラ撮影",
      close: "閉じる",
      useShot: "この写真を使う",
      cancel: "キャンセル",
      selectedFile: "選択したファイル",
      noFile: "まだ写真が選ばれていません",
      characterTone: "キャラクターの方向",
      toneHint: "結果がぶれないように、先に見たい役の方向を選んでください。",
      toneMale: "男性役寄り",
      toneFemale: "女性役寄り",
      quickCheck: "アップロード前のかんたん確認",
      checking: "この写真でそのまま進めてもよさそうか、軽く確認しています。少し待ってください。",
      quickCheckHint: "顔が見えやすい写真かを軽く確認します。この段階が省略されても結果は見ることができます。",
      notesTitle: "かんたんメモ",
      notes: [
        "見た目の評価はせず、雰囲気とキャラクター感だけを見ます。",
        "1人だけ写った写真のほうが結果がすっきり出やすいです。",
        "写真がぼやけている場合は別の写真をお願いすることがあります。",
      ],
      submit: "キャスティング結果を見る",
      submitting: "結果を準備しています...",
      webcamNotSupported: "このブラウザではウェブカメラ撮影に対応していません。",
      webcamOpenError: "カメラを開けませんでした。権限を確認するか、写真アップロードを使ってください。",
      captureError: "撮影画像を準備できませんでした。もう一度お試しください。",
      filePrepError: "写真の準備中に問題が発生しました。もう一度お試しください。",
    },
    share: {
      native: "共有",
      instagram: "Instagram",
      facebook: "Facebook",
      copyLink: "リンクをコピー",
      kakao: "カカオトーク",
      kakaoView: "結果を見る",
      instagramHint: "Instagramは文をコピーしてアプリに貼り付ける方式です。",
      kakaoHint: "カカオ共有キーを入れると直接共有できます。",
      copiedLink: "リンクをコピーしました。",
      copiedResultLink: "結果リンクをコピーしました。",
      copiedInstagram: "Instagram用の文をコピーしました。",
      copiedKakao: "カカオトーク用の文をコピーしました。",
    },
    resultUi: {
      loadingTitle: "結果を作成しています",
      emptyEyebrow: "まだ結果を読み込めていません",
      emptyTitle: "アップロードからやり直してください",
      emptyDescription: "写真をもう一度アップロードすると、キャラクター結果を作り直します。",
      headerEyebrow: "DRAMA CASTING TEST",
      headerTitle: "あなたのキャラクター結果が出ました",
      friendShare: "友だちに送りやすいひとこと",
      works: "こんな作品の雰囲気も似合います",
      actors: "近いムードの俳優レファレンス",
      actorsHint: "そっくり判定ではなく、今回の結果に近い雰囲気の参考です。",
      storageNote: "写真はブラウザ内で短時間だけ使い、長期保存はしません。",
      entertainmentNote: "これはエンタメ向けのキャラクターテストです。見た目の評価や順位づけはしません。",
    },
    footer: {
      privacyTitle: "プライバシー",
      privacyBody: "アップロードした写真は結果生成のために短時間だけ使い、長期保存はしません。",
      termsTitle: "利用案内",
      termsBody: "このサービスはエンタメ向けのキャラクターおすすめであり、診断や判定を行うものではありません。",
      contactTitle: "お問い合わせ",
      address: "Goyang-si, Gyeonggi-do, South Korea",
      email: "caelestis@empas.com",
    },
  },
} as const satisfies Record<Locale, Record<string, unknown>>;

export function getCopy(locale: Locale) {
  return pageCopy[locale];
}
